#!/usr/bin/env python

import yaml
import rospy

from controller import TwistController

if __name__ == "__main__":
    controller = None
    try:
        rospy.init_node('drive_controller')
        robot_name = rospy.get_param('~robot_name')
        controller = TwistController(robot_name)
        rate = rospy.Rate(rospy.get_param('~update_rate'))
        while not rospy.is_shutdown():
            controller.update()
            rate.sleep()

    except rospy.ROSInterruptException:
        pass

    finally:
        if controller is not None:
            controller.shutdown()
