#!/usr/bin/env python

import yaml
import rospy

from controller import TwistController

if __name__ == "__main__":
    controller = None
    try:
        rospy.init_node('motor_controller')

        params = None
        param_path = rospy.get_param('~motor_config_path')
        with open(param_path, 'r') as f:
            params = yaml.load(f.read())
        rospy.set_param('motors', params)

        controller = TwistController(params)
        rate = rospy.Rate(params['drive_rate'])
        while not rospy.is_shutdown():
            controller.drive()
            rate.sleep()

    except rospy.ROSInterruptException:
        pass

    finally:
        if controller is not None:
            controller.shutdown()
